version: "3.9"
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    networks:
      mini_project:    
   # volumes:
    #  - my-db:/var/lib/mysql
  applicationService:
    build: C:/Program Files (x86)/Jenkins/workspace/timesheet-ci
    image: myapp
    ports:
      - "8090:8090"
    restart: always
    depends_on:
      - db
    networks:
      mini_project:
networks:
  mini_project:
    driver: bridge
#volumes:
 # my-db: C:/Users/Mejri Wajih/Desktop/db